// <auto-generated />
namespace MyShop.DataAcess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BasketItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasketItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121807575_BasketItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
